version: "3.3"

services:
  dev:
    image: tg2fibery:latest
    volumes:
      - type: bind
        source: ./
        target: /root
    depends_on:
      - mountebank

  mountebank:
    image: andyrbell/mountebank
